# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  winthropmedicalaffiliates.org:
    site_hosts:
      - winthropmedicalaffiliates.dev
    site_title: Winthrop Medical Affiliates
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    admin_user: admin
    admin_password: admin
    admin_email: admin@winthropmedicalaffiliates.dev
    multisite:
      enabled: true
    ssl:
      enabled: true
      provider: self-signed
    cache:
      enabled: false
    env:
      wp_home: http://winthropmedicalaffiliates.dev
      wp_siteurl: http://winthropmedicalaffiliates.dev
      db_name: winthropmedicalaffiliates_org_development
      db_user: winthropmedicalaffiliates_org
      db_password: w3bma$t3r
